[build]
  base = "sepsisguard-react"
  publish = "sepsisguard-react/dist"
  command = "cd sepsisguard-react && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
